# Generated by Django 5.2.8 on 2025-11-25 20:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdaptationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "conditions",
                    models.JSONField(
                        default=list,
                        help_text="List of condition types this template addresses",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(default=dict, help_text="Full settings object"),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Available to all schools"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for global templates",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptation_templates",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "adaptation_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_identifier",
                    models.CharField(
                        help_text="School's student ID (anonymised)", max_length=100
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="First name only for privacy",
                        max_length=100,
                    ),
                ),
                (
                    "year_group",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(13),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes about the student"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "student_profiles",
                "ordering": ["display_name", "student_identifier"],
                "unique_together": {("school", "student_identifier")},
            },
        ),
        migrations.CreateModel(
            name="AdaptationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reading_year_level",
                    models.IntegerField(
                        default=8,
                        help_text="Target reading level (year group)",
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(13),
                        ],
                    ),
                ),
                (
                    "max_sentence_length",
                    models.IntegerField(
                        default=15,
                        help_text="Maximum words per sentence",
                        validators=[
                            django.core.validators.MinValueValidator(6),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "vocabulary_simplification",
                    models.IntegerField(
                        default=5,
                        help_text="1=maximum simplification, 10=no simplification",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "literal_language_mode",
                    models.BooleanField(
                        default=False, help_text="Remove idioms and figurative language"
                    ),
                ),
                (
                    "literal_language_intensity",
                    models.IntegerField(
                        default=5,
                        help_text="How aggressively to replace figurative language",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "syllable_breaking",
                    models.BooleanField(
                        default=False, help_text="Add syllable breaks to longer words"
                    ),
                ),
                (
                    "key_word_highlighting",
                    models.BooleanField(
                        default=True, help_text="Bold action words and key information"
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        choices=[
                            ("arial", "Arial"),
                            ("verdana", "Verdana"),
                            ("opendyslexic", "OpenDyslexic"),
                            ("lexie", "Lexie Readable"),
                            ("comic_sans", "Comic Sans MS"),
                        ],
                        default="arial",
                        max_length=50,
                    ),
                ),
                (
                    "font_size",
                    models.IntegerField(
                        default=14,
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "line_spacing",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(3.0),
                        ],
                    ),
                ),
                (
                    "letter_spacing",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage increase in letter spacing",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "background_colour",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("cream", "Cream (#FFF8E7)"),
                            ("light_yellow", "Light Yellow (#FFFACD)"),
                            ("light_blue", "Light Blue (#E6F3FF)"),
                            ("light_pink", "Light Pink (#FFE4E1)"),
                            ("light_green", "Light Green (#E8F5E9)"),
                        ],
                        default="cream",
                        max_length=20,
                    ),
                ),
                (
                    "text_colour",
                    models.CharField(
                        choices=[
                            ("black", "Black (#000000)"),
                            ("dark_grey", "Dark Grey (#333333)"),
                            ("navy", "Navy (#1a1a2e)"),
                        ],
                        default="dark_grey",
                        max_length=20,
                    ),
                ),
                (
                    "visual_density",
                    models.IntegerField(
                        default=5,
                        help_text="1=maximum spacing, 10=compact",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "questions_per_section",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "numbered_steps",
                    models.BooleanField(
                        default=True, help_text="Always number multi-step instructions"
                    ),
                ),
                (
                    "progress_indicators",
                    models.BooleanField(
                        default=True, help_text="Show question X of Y indicators"
                    ),
                ),
                (
                    "section_breaks",
                    models.BooleanField(
                        default=True, help_text="Add clear section breaks"
                    ),
                ),
                (
                    "reference_panels",
                    models.BooleanField(
                        default=False,
                        help_text="Include reference boxes for formulas/info",
                    ),
                ),
                (
                    "scaffolded_answers",
                    models.BooleanField(
                        default=False, help_text="Provide step-by-step answer templates"
                    ),
                ),
                (
                    "explicit_instructions",
                    models.BooleanField(
                        default=True,
                        help_text="Make all instructions completely explicit",
                    ),
                ),
                (
                    "tts_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable text-to-speech"
                    ),
                ),
                (
                    "tts_speed",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                ("tts_voice", models.CharField(default="default", max_length=50)),
                (
                    "word_highlighting",
                    models.BooleanField(
                        default=False, help_text="Highlight words as they are read"
                    ),
                ),
                (
                    "timer_display",
                    models.CharField(
                        choices=[
                            ("hide", "Hidden"),
                            ("show", "Visible"),
                            ("warnings", "Visible with warnings"),
                        ],
                        default="show",
                        max_length=20,
                    ),
                ),
                (
                    "feedback_style",
                    models.CharField(
                        choices=[
                            ("neutral", "Neutral"),
                            ("encouraging", "Encouraging"),
                            ("minimal", "Minimal"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "encouragement_prompts",
                    models.BooleanField(
                        default=False, help_text="Include encouraging messages"
                    ),
                ),
                (
                    "anxiety_reduction",
                    models.BooleanField(
                        default=False, help_text="Use calming language and formatting"
                    ),
                ),
                (
                    "first_language",
                    models.CharField(
                        default="en",
                        help_text="ISO language code for first language",
                        max_length=10,
                    ),
                ),
                (
                    "translation_mode",
                    models.CharField(
                        choices=[
                            ("none", "No translation"),
                            ("glossary", "Bilingual glossary only"),
                            ("full", "Full translation"),
                            ("side_by_side", "Side-by-side bilingual"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptation_settings",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "adaptation_settings",
            },
        ),
        migrations.CreateModel(
            name="StudentCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("dyslexia", "Dyslexia"),
                            ("autism", "Autism Spectrum Condition"),
                            ("adhd", "ADHD"),
                            ("dyscalculia", "Dyscalculia"),
                            ("visual_processing", "Visual Processing Difficulties"),
                            ("auditory_processing", "Auditory Processing Difficulties"),
                            ("working_memory", "Working Memory Difficulties"),
                            ("processing_speed", "Slow Processing Speed"),
                            ("anxiety", "Test/Performance Anxiety"),
                            ("eal", "English as Additional Language"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("significant", "Significant"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "diagnosed",
                    models.BooleanField(
                        default=False, help_text="Whether this is a formal diagnosis"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "first_language",
                    models.CharField(
                        blank=True,
                        help_text="For EAL condition - student's first language",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "student_conditions",
                "unique_together": {("student_profile", "condition_type")},
            },
        ),
        migrations.CreateModel(
            name="SubjectAdaptation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("mathematics", "Mathematics"),
                            ("science", "Science"),
                            ("history", "History"),
                            ("geography", "Geography"),
                            ("languages", "Modern Languages"),
                            ("art", "Art & Design"),
                            ("music", "Music"),
                            ("pe", "Physical Education"),
                            ("computing", "Computing"),
                            ("dt", "Design & Technology"),
                            ("re", "Religious Education"),
                            ("pshe", "PSHE"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "override_settings",
                    models.JSONField(
                        default=dict,
                        help_text="Only the settings that differ from core settings",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_adaptations",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "subject_adaptations",
                "unique_together": {("student_profile", "subject")},
            },
        ),
    ]
