# Generated by Django 5.2.8 on 2025-11-25 20:34

import assessments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=50)),
                ("year_group", models.IntegerField(blank=True, null=True)),
                ("original_file", models.FileField(upload_to="assessments/originals/")),
                (
                    "original_file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("image", "Image"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("page_count", models.IntegerField(default=1)),
                (
                    "content_flags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flags like {quotations: true, code: false, maths: true}",
                    ),
                ),
                (
                    "protected_terms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Subject-specific terms to preserve",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Special instructions for adaptation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdaptedAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adapted_content",
                    models.TextField(
                        help_text="The AI-adapted content in markdown/HTML"
                    ),
                ),
                (
                    "adaptation_prompt",
                    models.TextField(
                        blank=True, help_text="The prompt used for adaptation"
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        blank=True, help_text="Model used for adaptation", max_length=50
                    ),
                ),
                ("ai_tokens_used", models.IntegerField(default=0)),
                ("adaptation_time_seconds", models.FloatField(default=0)),
                (
                    "validation_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Results from automated validation",
                    ),
                ),
                ("validation_warnings", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_edit", "Needs Editing"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("manually_edited", models.BooleanField(default=False)),
                (
                    "edited_content",
                    models.TextField(blank=True, help_text="Teacher-edited version"),
                ),
                (
                    "output_pdf",
                    models.FileField(
                        blank=True,
                        upload_to=assessments.models.adapted_assessment_upload_path,
                    ),
                ),
                (
                    "output_docx",
                    models.FileField(
                        blank=True,
                        upload_to=assessments.models.adapted_assessment_upload_path,
                    ),
                ),
                ("output_html", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        upload_to=assessments.models.adapted_assessment_upload_path,
                    ),
                ),
                ("audio_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adaptation_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.adaptationtemplate",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_adaptations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adapted_assessments",
                        to="students.studentprofile",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adapted_versions",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "db_table": "adapted_assessments",
                "ordering": ["-created_at"],
            },
        ),
    ]
