# Generated by Django 5.2.8 on 2025-11-25 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Email domain for verification",
                        max_length=255,
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("max_students", models.IntegerField(default=50)),
                ("max_assessments_per_month", models.IntegerField(default=100)),
                ("max_adaptations_per_month", models.IntegerField(default=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "schools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UsageTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.DateField(help_text="First day of the month")),
                ("adaptations_count", models.IntegerField(default=0)),
                ("ai_tokens_used", models.BigIntegerField(default=0)),
                ("storage_bytes_used", models.BigIntegerField(default=0)),
                ("assessments_uploaded", models.IntegerField(default=0)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "usage_tracking",
                "ordering": ["-month"],
                "unique_together": {("school", "month")},
            },
        ),
    ]
