# Generated by Django 5.2.8 on 2025-11-25 20:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("preserve_quotations", "Preserve Quotations"),
                            ("preserve_maths", "Preserve Mathematical Notation"),
                            ("preserve_code", "Preserve Code"),
                            ("preserve_diagrams", "Preserve Diagram References"),
                            ("preserve_poetry", "Preserve Poetry Format"),
                            ("preserve_script", "Preserve Script Format"),
                            ("never_answer", "Never Answer Questions"),
                            ("never_add_info", "Never Add New Information"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(help_text="The rule text to include in prompts"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "content_rules",
            },
        ),
        migrations.CreateModel(
            name="IdiomDictionary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idiom", models.CharField(max_length=255, unique=True)),
                ("literal_meaning", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category like weather, body, animals, etc.",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "idiom_dictionary",
                "ordering": ["idiom"],
            },
        ),
        migrations.CreateModel(
            name="SubjectTerms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=50, unique=True)),
                (
                    "terms",
                    models.JSONField(
                        default=list,
                        help_text="List of protected terms for this subject",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Subject terms",
                "db_table": "subject_terms",
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("dyslexia", "Dyslexia"),
                            ("autism", "Autism Spectrum Condition"),
                            ("adhd", "ADHD"),
                            ("dyscalculia", "Dyscalculia"),
                            ("visual_processing", "Visual Processing Difficulties"),
                            ("auditory_processing", "Auditory Processing Difficulties"),
                            ("working_memory", "Working Memory Difficulties"),
                            ("processing_speed", "Slow Processing Speed"),
                            ("anxiety", "Test/Performance Anxiety"),
                            ("eal", "English as Additional Language"),
                            ("core_rules", "Core Rules (Always Applied)"),
                            ("output_format", "Output Format Instructions"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "prompt_section",
                    models.TextField(help_text="The actual prompt instructions"),
                ),
                (
                    "intensive_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Additional instructions for significant severity",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this prompt"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prompt_templates",
                "ordering": ["condition_type", "-version"],
                "unique_together": {("condition_type", "version")},
            },
        ),
    ]
